name: CI/CD Pipeline biblioteca-pessoal

# Gatilhos: roda em push ou pull request para a branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o código do repositório
      - uses: actions/checkout@v4

      # 2. Configura o JDK 21
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Roda o build e os testes.
      - name: Build e Testes com Maven
        run: mvn -B verify